version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: development_teams
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: teams_dev
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
