version: '3.9'
services:
  test-db:
    image: postgres:15
    ports:
      - "5433:5432"  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db